namespace Mercatec.Helpers
{
    enum ListToolbarMode
    {
        Default,
        Cancel,
        CancelDelete
    };

    enum DetailToolbarMode
    {
        Default,
        BackEditdDelete,
        CancelSave
    };
}
