namespace Mercatec.Helpers.Services
{
    interface INavigationService
    {
        Boolean CanGoBack  { get; };

        void GoBack();
        void Initialize(Microsoft.UI.Xaml.Controls.Frame Frame);

        Boolean Navigate(Windows.UI.Xaml.Interop.TypeName ViewModelType);
        Boolean Navigate(Windows.UI.Xaml.Interop.TypeName ViewModelType, Object Parameter);

        void CreateNewView(Windows.UI.Xaml.Interop.TypeName ViewModelType);
        void CreateNewView(Windows.UI.Xaml.Interop.TypeName ViewModelType, Object Parameter);
    }
}
