import "Mercatec.Helpers.Services.ICommonServices.idl";
import "Mercatec.Helpers.Services.IContextService.idl";
import "Mercatec.Helpers.Services.IDialogService.idl";
import "Mercatec.Helpers.Services.ILogService.idl";
import "Mercatec.Helpers.Services.INavigationService.idl";

namespace Mercatec.Services
{
    typedef Mercatec.Helpers.Services.ICommonServices    ICommonServices;
    typedef Mercatec.Helpers.Services.IContextService    IContextService;
    typedef Mercatec.Helpers.Services.IDialogService     IDialogService;
    typedef Mercatec.Helpers.Services.ILogService        ILogService;
    typedef Mercatec.Helpers.Services.INavigationService INavigationService;
}
