namespace Mercatec.Helpers.Services
{
    interface INavigationService
    {
        Boolean IsMainView { get; };
        Boolean CanGoBack  { get; };

        void GoBack();
        void Initialize(Microsoft.UI.Xaml.Controls.Frame Frame);

        Boolean Navigate(Windows.UI.Xaml.Interop.TypeName ViewModelType);
        Boolean Navigate(Windows.UI.Xaml.Interop.TypeName ViewModelType, Object Parameter);

        Windows.Foundation.IAsyncOperation<Int32> CreateNewViewAsync(Windows.UI.Xaml.Interop.TypeName ViewModelType);
        Windows.Foundation.IAsyncOperation<Int32> CreateNewViewAsync(Windows.UI.Xaml.Interop.TypeName ViewModelType, Object Parameter);
        Windows.Foundation.IAsyncAction CloseViewAsync();
    }
}
