import "Mercatec.Helpers.ViewModels.IModel.idl";

namespace Mercatec.Helpers.ViewModels
{
    interface IEntity
    {
        Windows.Foundation.DateTime                                CreatedDate  { get; set; };
        Windows.Foundation.IReference<Windows.Foundation.DateTime> ModifiedDate { get; set; };
        Windows.Foundation.IReference<Windows.Foundation.DateTime> DeletedDate  { get; set; };
        Boolean                                                    IsEdit       { get; set; };
        Boolean                                                    IsDelete     { get; set; };
    };
}
