import "Mercatec.Helpers.Delegates.idl";

namespace Mercatec.Helpers.Services
{
    interface IContextService
    {
        void Initialize(Microsoft.UI.Dispatching.DispatcherQueue Dispatcher);
        Boolean Run(Microsoft.UI.Dispatching.DispatcherQueueHandler Action);
    }
}
