// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

import "Mercatec.Services.Auths.Models.PassportDevice.idl";

namespace Mercatec.Services.Auths.Models
{
    [bindable]
    [default_interface]
    runtimeclass UserAccount
    {
        UserAccount();
        Guid   UserId   { get; set; };
        String UserName { get; set; };
        String Password { get; set; };
        IVector<PassportDevice> PassportDevices { get; set; };
    }
}
