namespace Mercatec.WinUIEx
{
    /// <summary>
    /// Information about the ZOrder of the window
    /// </summary>
    /// <seealso cref="WindowEx.ZOrderChanged"/>
    /// <seealso cref="WindowEx.OnZOrderChanged"/>
    [bindable]
    [default_interface]
    runtimeclass ZOrderInfo 
    {
        ZOrderInfo();

        /// <summary>
        /// Gets a value indicating whether the window's Z Order is at the top.
        /// </summary>
        /// <seealso cref="Microsoft.UI.Windowing.AppWindowChangedEventArgs.IsZOrderAtTop"/>
        Boolean IsZOrderAtTop { get; set; };

        /// <summary>
        /// Gets a value indicating whether the window's Z Order is at the bottom.
        /// </summary>
        /// <seealso cref="Microsoft.UI.Windowing.AppWindowChangedEventArgs.IsZOrderAtBottom"/>
        Boolean IsZOrderAtBottom { get; set; };

        /// <summary>
        /// Gets the id of the window this window is below.
        /// </summary>
        /// <seealso cref="Microsoft.UI.Windowing.AppWindowChangedEventArgs.ZOrderBelowWindowId"/>
        Microsoft.UI.WindowId ZOrderBelowWindowId { get; set; };
    }
}
