import "Mercatec.Application.EffectMode.idl";

namespace Mercatec.Application
{
    [default_interface]
    runtimeclass LoginPage : Microsoft.UI.Xaml.Controls.Page
    {
        LoginPage();
    }
}
