// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Mercatec.Application
{
    [default_interface]
    runtimeclass NamePasswordControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        NamePasswordControl();
        Int32 MyProperty;
    }
}
