// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Mercatec.Application
{
    [bindable]
    [default_interface]
    runtimeclass NamePasswordControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        NamePasswordControl();
        String UserName { get; set; };
        String Password { get; set; };
        Microsoft.UI.Xaml.Input.ICommand LoginWithPasswordCommand { get; set; };
        void Focus();

        static Microsoft.UI.Xaml.DependencyProperty UserNameProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty PasswordProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty LoginWithPasswordCommandProperty{ get; };
    }
}
