// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Mercatec.Application
{
    [default_interface]
    runtimeclass WindowsHelloControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        WindowsHelloControl();
        Int32 MyProperty;
    }
}
