// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Mercatec.Application
{
    [bindable]
    [default_interface]
    runtimeclass WindowsHelloControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        WindowsHelloControl();
        String UserName { get; set; };
        Microsoft.UI.Xaml.Input.ICommand LoginWithWindowHelloCommand { get; set; };

        static Microsoft.UI.Xaml.DependencyProperty UserNameProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty LoginWithWindowHelloCommandProperty{ get; };
    }
}
