import "Mercatec.ViewModels.idl";


namespace Mercatec.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass User : IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        User();
        UInt64 UserId;
        String UserName;
        String Email;
        String Phone;
        String Address;
        String Password;
    }
}
