// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Mercatec.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass User
    {
        User();
        Int32 MyProperty;
    }
}
