namespace Mercatec.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass User : Mercatec.Helpers.ViewModels.IModel, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        User();
        Guid   UserId;
        String UserName;
        String Email;
        String Phone;
        String Address;
        String Password;
    }
}
