namespace Mercatec.Helpers.ViewModels
{
    [bindable]
    [default_interface]
    unsealed runtimeclass ObservableObject : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ObservableObject();
        Boolean IsEmpty { get; set; };
        protected void Merge(ObservableObject Source);

        void NotifyPropertyChanged(String PropertyName);
        void NotifyChanges();
    }
}
