// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Mercatec.Helpers
{
    [default_interface]
    runtimeclass Class
    {
        Class();
        Int32 MyProperty;
    }
}
