import "Mercatec.Helpers.ViewModels.INotifyPropertyChanged.idl";

namespace Mercatec.Helpers.ViewModels
{
    [bindable]
    [default_interface]
    unsealed runtimeclass ObservableObject : INotifyPropertyChanged
    {
        ObservableObject();
        Boolean IsEmpty { get; set; };
        overridable void Merge(ObservableObject Source);
    }
}
